// Departments data - converted from Python
const Departments = [
    {
        id: "1",
        title: "Section 1 — Apply AI",

        questions: [
            ["How can humans influence the outcome of machine learning? Through…",
             [
                 "...calculation of the accuracy of the prediction",
                 "...randomized division into test and training data",
                 "...selection of the model",
                 "...abstraction of the model"
             ], 2],

            ["An AI technology is trained with labeled images to recognize whether a particular person is in an image or not. What happens in the training phase to improve the system when a false identification occurs?",
             [
                 "Strengthening or weakening the connections in the network",
                 "Ask the algorithm to remember the image the AI technology misidentifies",
                 "Delete the images",
                 "Change the image's caption so that the AI technology no longer misidentifies it"
             ], 0],

            ["Which of the following processes does not use natural language processing (NLP) technologies?",
             [
                 "Analysis of clinical text recordings",
                 "Gesture-controlled robot",
                 "Story generator",
                 "Question and answer tool"
             ], 1],
        ]
    },

    {
        id: "2",
        title: "Section 2 — Create AI",

        questions: [
            ["The game statistics of a basketball team are to be used to predict how many games it will win in the current season. Which algorithm is best suited to make this prediction?",
             [
                 "Classification",
                 "Regression",
                 "Clustering",
                 "Object detection"
             ], 1],

            ["When we use machine learning techniques in a text recognition system:",
             [
                 "We present the system with a series of sample texts, and after processing them, the system can recognize only texts that correspond exactly to these examples",
                 "We give the system a series of example texts, and after processing, the system can recognize texts similar to these examples (i.e., it recognizes new texts that it has never seen before)",
                 "We give the system a set of example texts; after processing, the system can recognize any text we give it",
                 "We give the system a series of sample texts, and after processing them, the system can recognize any text, image, or sound we present to it"
             ], 1],

            ["In which of these areas is AI typically applied?",
             [
                 "Detecting credit card fraud",
                 "Cryptocurrency mining",
                 "Web tracking",
                 "Encryption for instant messaging services"
             ], 0],
        ]
    },

    {
        id: "3",
        title: "Section 3 — Detect AI",

        questions: [
            ["Which of these applications does NOT use AI?",
             [
                 "A medical system that analyzes patterns on tissue images to determine whether cancer is present",
                 "A chatbot on a website that answers predefined questions",
                 "Voice assistants recognize, understand, and respond to spoken language",
                 "Face-lock function on cell phones to recognize and distinguish users' faces"
             ], 1],

            ["How is AI already being used in urbanization issues today?",
             [
                 "Predictive maintenance forecast for water pipes",
                 "Regulation of the housing market",
                 "Optimized settlement strategy for inner cities",
                 "Forecasting the volume of passengers on public transport"
             ], 3],

            ["What characteristics differentiate AI from previous IT applications?",
             [
                 "Learning ability and independence",
                 "Ability to process data and ease of use",
                 "Speed and ability to process data",
                 "Location-independent access and data security"
             ], 0],
        ]
    },

    {
        id: "4",
        title: "Section 4 — Generative AI",

        questions: [
            ["What does \"generative\" mean in the context of artificial intelligence?",
             [
                 "It refers to quickly retrieving existing content from a database",
                 "It means that the AI can create new content on demand based on training data",
                 "It describes the ability to collect data from the Internet in real-time",
                 "It stands for the ability to summarize information from multiple sources"
             ], 1],

            ["Hallucinations in AI models refer to nonsensical or grammatically incorrect words or sentences generated by the model. Which of the following factors is least likely to cause hallucinations?",
             [
                 "The model is trained using noisy or erroneous data",
                 "The model is trained with too much data",
                 "The model is not trained with enough data",
                 "The model is not given enough context"
             ], 1],

            ["Which of the following strategies is NOT particularly helpful for recognizing whether a generative AI created a video?",
             [
                 "Check that the color palette in the video remains consistent across different scenes, as AI-generated videos sometimes have color variations",
                 "Pay attention to object permanence to check whether objects that move out of the field of view reappear when the camera pans back",
                 "Check the movements of people and objects in the video for logical consistency to ensure that they comply with the laws of physics",
                 "Watch the video several times and pay attention to different details to notice possible errors"
             ], 0],
        ]
    },
{
        id: "5",
        title: "Section 5 — Understanding AI",

        questions: [
            ["How does a recommendation system of a streaming service based on AI work?",
             [
                 "It uses the data of all users to generate personalized recommendations",
                 "It uses all available data from users on the internet to make suggestions",
                 "It is based exclusively on the data of other users but not on your own",
                 "It only uses users' own data for recommendations"
             ], 0],

            ["What is a possible consequence of online search engines' AI-based personalization processes?",
             [
                 "A greater variety of information and opinions is presented",
                 "People can fall into filter bubbles with only affirmative content",
                 "People get the same results for the same search query",
                 "The search results become less relevant for the user"
             ], 1],

            ["Which of the following characteristics could indicate that a text was generated by an AI?",
             [
                 "The text is incorrect and contains many typos",
                 "The text is written in several languages",
                 "The text is perfectly structured but contains generic or repetitive phrases",
                 "The text contains strongly subjective opinions and emotions"
             ], 2],
        ]
    },
];
